// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mquvqeprxucgwgkztfpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xdXZxZXByeHVjZ3dna3p0ZnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMTM5MjIsImV4cCI6MjA2NDc4OTkyMn0.KdOEDWW2v0QtwMj2VOhtEbTgOl-OXo3gzOszXyGjf9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);